---
#Install Splunk for full instances
- hosts: SH, IDX, HF, UF
  connection: ssh
  gather_facts: no
  tasks:

#create the temporary splunk directory
  - file:
     path: /opt/temporary
     state: directory
     mode: 0755
#download and install splunk
  - get_url:
     url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.3&product=splunk&filename=splunk-7.0.3-fa31da744b51-linux-2.6-x86_64.rpm&wget=true
     dest: /opt/temporary/splunk703.rpm
  -file:
     path: /opt/temporary
     dest: absent

#Install Splunk for universal forwarder
- hosts: UF
  connection: ssh
  gather_facts: no
  tasks:

#create the temporary splunk directory
  - file:
     path: /opt/temporary
     state: directory
     mode: 0755
#download and install splunk
  - get_url:
     url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.3&product=universalforwarder&filename=splunkforwarder-7.0.3-fa31da744b51-linux-2.6-x86_64.rpm&wget=true
     dest: /opt/temporary/splunk703.rpm
  - file:
     path: /opt/temporary
     dest: absent